### ISSUE TITLE
Project still alive & Alternatives

### ISSUE THREAD

**Issue by katastrophe92** [redorescue/redorescue#117]
Hello GitHub! 
I just found this neat project and it looks promising but idk if I can trust it for my backups if in the past 2 years got no updates and bug reports got no answers. What are the open source alternatives to this backup app?
Thanks!

**Comment by harukodi** [comment]
> katastrophe92

Move over to rescuezilla! Today i got a virus xD so now i used it to restore my windows image works like a sharm!
