### ISSUE TITLE
Better feedback for partclone / pigz / split errors

### ISSUE THREAD

**Issue by zebradots** [redorescue/redorescue#20]
During the backup/restore process, there are a number of errors such as "Input/output error" and others that strongly suggest a bad connection to a drive, SMART errors, bad sectors, or hardware failure. Simply passing the partclone errors as-is may lead less technical users to think this is a failure of the software, rather than their hardware or network connection.

In the next release, certain error messages will be coupled with informative suggestions on what is likely causing the problem, and what steps can be taken to diagnose and/or correct the problem.

**Comment by agnivo007** [comment]
Adding more verbosity is certainly welcome! Good going...

**Comment by zebradots** [comment]
Inexperienced users tend to blame Redo when partclone reports an `Input/output error`. In reality the underlying issue is likely faulty hardware, a network disconnection, filesystem inconsistencies, or a bad cable. Error reporting is greatly improved now with https://github.com/redorescue/redorescue/commit/bc3266de2e5d43515c97117302a69394e42f68c6.
