### ISSUE TITLE
how to enter the password directly without entering the settings menu

### ISSUE THREAD

**Issue by candrapersada** [redorescue/redorescue#21]
Can't connect WIFI with a password directly without to network options?
![image](https://user-images.githubusercontent.com/36833664/88208621-b781c400-cc7b-11ea-8119-d0f05042a2be.png)

**Comment by zebradots** [comment]
> Can't connect WIFI with a password directly without to network options?

We're having trouble understanding the issue. Are you asking if it is possible to modify the system to connect to WiFi automatically, without having to enter the password?

**Comment by candrapersada** [comment]
not my intention is how to enter the password directly without entering the settings menu like this picture
![image](https://user-images.githubusercontent.com/36833664/88334052-60ebb700-cd5b-11ea-8a91-63d725308a96.png)
Besides that, when I click on the WIFI icon there is no menu to enter a password

**Comment by zebradots** [comment]
Understood! No, the only way to modify the network settings is to use the menu that you showed above. The live CD/USB interface does not contain all the packages a full-blown distribution like Ubuntu or Linux Mint offers, and may not work in the same way. However, if you would like to modify the ISO image to change what packages are installed, you can edit the `make` script to extend the package list to produce your own version!

**Comment by candrapersada** [comment]
how to get notifications for enter a password  connect WI-FI from redorescue
![gambar](https://user-images.githubusercontent.com/36833664/88355852-2ea87c80-cd90-11ea-823e-8956aae7e7ad.png)

**Comment by zebradots** [comment]
The screenshot above is not from Redo Rescue, and Redo Rescue is not intended to be a feature-complete operating system. Redo may not offer the same level of automatic detection of WiFi settings which results in a prompt for the password that looks like the one in this screenshot. In any case, the correct wireless settings can be entered via the network manager icon, and works as expected.

**It is worth pointing out that performing operations like system backups and restores over a wireless connection is ill-advised. It may work, but it's far more likely to fail or cause corruption of data during large transfers.**

**Comment by agnivo007** [comment]
One thing I'd like to add regarding wifi, a lot of people use broadcom b43 (new and old ver of chips especially in various dell/hp laptops) cards which are not auto supported or usable by default. There is a b43-fwcutter package in Debian along with dkms/kernel module support if you're interested in including it in the release.

**Comment by zebradots** [comment]
@agnivo007, you make a good point about wireless support. If interested, you may want to open a separate issue regarding that because this issue will probably be closed at some point, seeing as wireless otherwise functions fine (though it may require an additional step or dialog that a full-blown live OS doesn't).
