### ISSUE TITLE
Feature suggestions for advanced options (slicing, compression, etc.)

### ISSUE THREAD

**Issue by agnivo007** [redorescue/redorescue#22]
Image options : Slicing, compression etc...

- Choose Image slice size (we can go more than 4GB on all FS except FAT), No slicing.

- Choose compression algo/level (zstd is quite good on images)

What do you think? I'll add more if I find something later...

**Comment by agnivo007** [comment]
UI : After an operation is complete, ie- backup/restore/validate, there should be a "back to home" button next to "exit" button, in case one decides to do another operation.

**Comment by zebradots** [comment]
Options regarding slices and compression are more likely going to be for advanced users. If these options get added, it should be in a way that hides them until they are exposed in the UI with a click (e.g. "Advanced options").

**Comment by agnivo007** [comment]
Thanks for your consideration and time, looks like this project is heading in the right direction...

I'll be adding my inputs whenever something comes up in mind.

**Comment by agnivo007** [comment]
A few things came to my mind today (after booting 2.0.5 release on a Dell Latitude E6230 laptop):

1. Set an acceptable brightness level at boot.

Boots at full brightness by default, hurts eyes very much! Didn't find a way to reduce it to acceptable level.
Can it be set to say, 60% at boot by default? [This link might help you](https://ostechnix.com/how-to-adjust-monitor-brightness-from-command-line-in-linux/)

2. Enable F2FS support.

A lot of users, especially single board computer users who run Rasberry Pi, etc. use a SD card with F2FS and swear by it for longevity and performance of the filesystem. I, personally have a 64GB SD card plugged into my laptop and formatted as F2FS. I wished to make a backup there, but it wasn't detected by redorescue. Adding support requires adding f2fs.ko kernel module and f2fs-tools package, which would hardly add a MB only to the distro, but SoC users would praise you gladly for the support.

That's all for today...

**Comment by zebradots** [comment]
Hello @agnivo007! Thanks for your continued valuable input!

To better track these requests, please open a separate issue for each feature you think should be considered. Thanks again!
