### ISSUE TITLE
Add NFS support

### ISSUE THREAD

**Issue by zebradots** [redorescue/redorescue#23]
> What about NFS shares? Are they supported? Many users with a NAS use NFS shares...

_Originally posted by @agnivo007 in https://github.com/redorescue/redorescue/issues/17#issuecomment-667470786_

Excellent suggestion!

**Comment by zebradots** [comment]
This feature has been merged with https://github.com/redorescue/redorescue/commit/912772a75ad8118e52fd226b5c50aea9740381fb. Please report any issues with this feature. Thank you to @agnivo007 for suggesting this addition.

**Comment by agnivo007** [comment]
Thanks and good going! Will test when released.
