### ISSUE TITLE
Ignore partclone's initially incorrect percent complete output

### ISSUE THREAD

**Issue by zebradots** [redorescue/redorescue#25]
When restoring (and possibly when performing a backup), `partclone` may briefly report the wrong percent complete at the very beginning of the process, which causes the UI's progress bar to advance for a moment, and then retreat back to the correct value.

Redo is correctly reporting the values that are provided by `partclone`, but given that these values may not be accurate, it may be best to toss output that resembles this line:

`Elapsed: 00:00:01, Remaining: 00:01:39, Completed:  1.00%, 0.00byte/min,`

In this case, the process is nowhere near 1.00% complete, yet `partclone` reports this value first, maybe even before it has processed any data.

Ordinarily, the output reports the speed in GB/min, such as `5.82GB/min,`, so the lines that indicate `0.00byte/min,` are automatically suspect and can probably safely be ignored, since the very next output line received one second later is more accurate (and any process that is measured in "bytes per minute" would take a lifetime to complete anyway).

**Comment by agnivo007** [comment]
Hmm, maybe the 000 value is due to delay in creation of the file or reserving space... a nice fix to add.

**Comment by zebradots** [comment]
Yes, that's probably exactly what's happening. It's just weird that `partclone` would report 1.00% complete when that's clearly not true! Anyway, we now skip the UI update when the reported values match `1.00%` and `0.00byte/min` for restores. This may not affect backups or verification operations, but if it does, the same will apply to their respective ajax files.

Fixed in https://github.com/redorescue/redorescue/commit/c6526deac747c9fe9216393c1ffd7475c9cdfe05.
