### ISSUE TITLE
A simple touchscreen keyboard would be great for POS backups

### ISSUE THREAD

**Issue by IlgazC** [redorescue/redorescue#28]
Hello

We have 2 POS terminals (windows based) which doesn't have keyboard and only touchscreen. When I try to backup, on "save backup" option, it would be great to have a new folder so I can backup the other one to another folder. As keyboard is missing, I can't add/change folder name. It would be great to have a simple touchscreen keyboard which is accessible from dock.

**Comment by zebradots** [comment]
Are you referring to something like Debian's `matchbox-keyboard`? Here is a [screenshot](http://www.upubuntu.com/2011/07/virtual-keyboard-for-touchscreen.html).

**Comment by IlgazC** [comment]
Yes something with minimum dependencies which will just do the job.

**Comment by zebradots** [comment]
This feature was added in https://github.com/redorescue/redorescue/commit/19f71a9e7eb0dd13736f3eb4ac6ed283cc6754fb. The `matchbox-keyboard` didn't behave well and was very tiny, so we chose to go with `xvkbd` instead. This will be included in the next release.

**Comment by zebradots** [comment]
Added in 2.0.5 release.
