### ISSUE TITLE
Welcome message displayed every time application is restarted

### ISSUE THREAD

**Issue by zebradots** [redorescue/redorescue#31]
The "Welcome to Redo..." is designed to make users feel welcome instead of just dumping them into the application. It also draws attention to the other tools available through the start menu.

When an operation is completed within the application, clicking the button to start a new operation currently displays this same greeting again. Also if the application is closed for any reason, restarting a new instance results in the same behavior.

This is a one-time greeting that ideally should only be displayed once after booting into the GUI.

**Comment by zebradots** [comment]
With https://github.com/redorescue/redorescue/commit/33c2b14458ad84c2b37adefe68172838944f0994, this behavior has changed. When the application is launched, it will now check to see if the status file (`status.json`) exists. If not, the welcome greeting is displayed. To ensure this works properly when the application is formally closed with the `exit_app()` function, the `unlink` command was removed and the status file now has an empty object saved to it, so that the file is present on subsequent checks, even though it contains no data.

**Comment by agnivo007** [comment]
Good idea...

**Comment by zebradots** [comment]
Yeah, it was getting old in testing :)
