### ISSUE TITLE
Add brightness control for laptop devices

### ISSUE THREAD

**Issue by zebradots** [redorescue/redorescue#32]
Laptop brightness control is currently possible through cryptic command line options, but there should be an easy way to adjust it. This issue was initially raised [here](https://github.com/redorescue/redorescue/issues/22#issuecomment-679928792) by @agnivo007.

**Comment by zebradots** [comment]
This package addition was applied with https://github.com/redorescue/redorescue/commit/a4117b9ace6113f87c96e929636d1e69e314dc4e.

**Comment by agnivo007** [comment]
Will test when new build is released...

**Comment by zebradots** [comment]
Included in 2.0.6 release.
