### ISSUE TITLE
Enable F2FS support

### ISSUE THREAD

**Issue by agnivo007** [redorescue/redorescue#35]
A lot of users, especially single board computer users who run Rasberry Pi, etc. use a SD card with F2FS and swear by it for longevity and performance of the filesystem. I, personally have a 64GB SD card plugged into my laptop card reader formatted as F2FS. I wished to make a backup there, but it wasn't detected by redorescue. Adding support requires f2fs.ko kernel module and f2fs-tools package, which would hardly add a MB only to the distro, but SBC users would praise you gladly for the support.

**Comment by zebradots** [comment]
Just to clarify, the aim would be to save backups **to** the F2FS filesystem (and then also restore **from** same), as another recognized filesystem available for the storage of backup images, correct?

**Comment by agnivo007** [comment]
Read/write from/to partitions to backup/restore as well as the backup folder.
I may have a F2FS backup destination as well as a source F2FS partition.

**Comment by zebradots** [comment]
Of course, `partclone` does not support F2FS, so the image would be essentially a byte-for-byte clone, similar to those created with `dd`. This is still something you would be okay with?

**Comment by agnivo007** [comment]
That will certainly do, and dd image will be compressed finally anyways...

Thanks for looking into the request. When do you intend to release 2.0.6, just for info?

**Comment by zebradots** [comment]
Added with latest commit (https://github.com/redorescue/redorescue/commit/6fc7f698d7085c877d83276d505c1879d63d047b). Thank you for your continued input and support for Redo!

**Comment by agnivo007** [comment]
Thanks for the feature, will definitely test in the next official iso.

**Comment by zebradots** [comment]
Included in 2.0.6. Thanks for your patience!
