### ISSUE TITLE
Is the display resolution hardcoded?

### ISSUE THREAD

**Issue by agnivo007** [redorescue/redorescue#41]
Seems like the display resolution is hard-coded to 1024x768. Even if display settings is opened for manual setup, it shows Auto (which sets to 1024x768) and 1024x768 only. Auto or redo at boot doesn't seem to use the native resolution of the monitor.

**Comment by zebradots** [comment]
The display is not hard-coded, but support for all resolutions may be limited by the fact that the non-free firmware is not presently included in the built images. You can change this yourself with a little tweaking, but it's something we're considering modifying in the future. This, combined with the new Debian 10 base, will offer much greater hardware support going forward!

**Comment by agnivo007** [comment]
The system in question is an old HP thin client T610 with AMD 6320 IGP which is well supported by radeon driver in all debian versions.
Yes, I eagerly look forward to the Debian 10 base for redo. Will check the boot line edit...

**Comment by zebradots** [comment]
If Debian 9 supports it, then it is likely that merely editing the boot line and removing `vga=791` will correct this for you, but the situation should certainly improve with future updates.

**Comment by zebradots** [comment]
Closing this issue as there are workarounds and the hardware support should be vastly improved with Debian 10.
