### ISSUE TITLE
Using USB live boots to Debian terminal login prompt with some video cards

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [redorescue/redorescue#47]
I use Rufus to make a bootable usb and I am presented with a login screen. After that nothing happens. Using 3.0.0

**Comment by IlgazC** [comment]
Does the "login screen" say "GRUB"? It must be the boot manager shell. Not a login prompt.

**Comment by PROBLEMCHYLD** [comment]
No

**Comment by zebradots** [comment]
1. Have you tried using a different USB stick?
2. Have you tried using a different image writer (Balena etcher, `dd`, etc.)?
3. What does the login screen look like? Can you provide a screenshot?

**Comment by PROBLEMCHYLD** [comment]
USB is fine, Rufus works and never had any problems with it. Version 2.0.7 had no issues.

**Comment by engstk** [comment]
This happened to me in 2 different UEFI systems.
Seems like some derp on resolution maybe some firmware is missing?
Had something similar with my Navi 10 when it came out, had kernel support, but fw package was old/missing.
Quick tested on AMD Zen 2+5700 XT and the other system Intel 10th Gen with integrated graphics.
On a BIOS VM is worked normal.

**Comment by zebradots** [comment]
Seems like this is related to the `linux-firmware-nonfree` modules. The path of least resistance here is probably going to be to add these non-free firmware blobs to enable certain video hardware to work properly, with the added benefit that other hardware will also gain support (e.g. certain wireless adapters).

**Comment by zebradots** [comment]
We will get this changed soon with a new release, since it looks like Debian 10's kernel requires the non-free firmware for hardware that previously did not require it on Debian 9.

**Comment by agnivo007** [comment]
I confirm non-free firmware packages are needed. Faced similar issue when the firmware-amd-graphics had to be installed else X won't start on a minimal debian install and dropped to console login.

**Comment by zebradots** [comment]
Support for non-free firmware added with https://github.com/redorescue/redorescue/commit/ea7641c477f2f7dc9e4cc43a63b3254d20280d7d. This should fix the issue for those users who found themselves at a console login prompt with 3.0.0, rather than booting into the actual graphical user interface.

**Comment by zebradots** [comment]
Release 3.0.1 is complete, so we're going to close this issue now.
