### ISSUE TITLE
Redo fails to restore due to incorrect NVMe partition names

### ISSUE THREAD

**Issue by Sfinx** [redorescue/redorescue#50]
While restoring redo creates the right partition table but failed to get the right partitions names so it tries to restore to unexistent partitions. See attachment - the paritions are simple nvme ones, nvme0n1p[123] but redo ones are from the sky. To reproduce screenshot just boot to redo, make backup and try to restore at the same box.
[bug.pdf](https://github.com/redorescue/redorescue/files/5423640/bug.pdf)

**Comment by zebradots** [comment]
Thank you @Sfinx for reporting this issue and helping pinpoint the underlying problem! If you are able to paste the contents of the `/tmp/status.json` file just after the operation fails, that would be extremely helpful.

**Comment by zebradots** [comment]
Is this problem limited to **restore** operations, or does the **verify** also fail?

**Comment by Sfinx** [comment]
Too lazy to boot the real box - please see the attached status from Qemu running fake nvme - the Redo error is the same.

[status.json.gz](https://github.com/redorescue/redorescue/files/5430206/status.json.gz)

Verify do not fail

**Comment by zebradots** [comment]
@Sfinx, thank you very much for providing detailed information to help identify the cause of this bug. It has been fixed with commit https://github.com/redorescue/redorescue/commit/f8eba426ce85795383c5d3104588e73cee34ea88 and will be included in the next release.

**Comment by Sfinx** [comment]
Thanks ! Will try and report. Having a small FR's for Redo so it can become more useful :

- add some text config file option to ISO where if present you can set there VNC pass, SSHFS creds or other options that will allow to use Redo without keyboard/monitor

**Comment by Sfinx** [comment]
Tested in Qemu - restore is working as expected. Thanks !
