### ISSUE TITLE
[Share your info] v3.x Boot/Hardware Compatibility Report Thread

### ISSUE THREAD

**Issue by agnivo007** [redorescue/redorescue#51]
This thread is **not about an issue or bug** but to report your experiences on the v3.x release which is the first ever transition to UEFI (with optional secure boot) and Debian 10 base. I have been keeping a close watch on the issues posted by users regarding grub/booting mainly on different types of proprietary systems. This is to collect report/feedback from users whether Redo is booting/working for you along with your system info. Other users will find it useful to cross-check compatibility and the developer would also be helped to address specific system issues I hope.

Optional (recommended): You can run the following command from any linux terminal on the machine and post below:
Redo does not bundle inxi package, you can use another linux distro (live also) to get the output.
`sudo inxi -CDGMmnz`

Please post in the following format: (Replace with your data)
___
Redo Rescue Version : v3.x
System Manufacturer / Model : 
Booting Mode : UEFI / BIOS-Legacy
SecureBoot : Enabled / Disabled / NA
Booting to Redo App? : Yes / No
Working as expected? : Yes / No
Other Comments : 

System Info : 
`Paste your inxi output here in <> code tags`
___

**Comment by agnivo007** [comment]
Redo Rescue Version : v3.0.1
System Manufacturer / Model : HP / Thin Client T610
Booting Mode : UEFI
SecureBoot : Disabled
Booting to Redo App? : Yes
Working as expected? : Yes
Other Comments : I use a Ventoy (www.ventoy.net) multiboot usb drive, just copy the ISO and boot off it.

System Info :
`System:    Host: hp Kernel: 4.19.0-12-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 
           info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 Distro: MX-19.2_base_x64 patito feo Sept 28  2020 
           base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Desktop System: Hewlett-Packard product: HP t610 WW Thin Client v: N/A serial: <filter> Chassis: type: 4 
           serial: <filter> 
           Mobo: Hewlett-Packard model: 17E2 serial: <filter> UEFI: Hewlett-Packard v: K30 v01.20 date: 03/10/2015 
CPU:       Topology: Dual Core model: AMD G-T56N bits: 64 type: MCP arch: Bobcat L1 cache: 128 KiB L2 cache: 512 KiB 
           flags: lm nx pae sse sse2 sse3 sse4a ssse3 svm bogomips: 6586 
           Speed: 1034 MHz min/max: 825/1650 MHz Core speeds (MHz): 1: 833 2: 887 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 6320] vendor: Hewlett-Packard driver: radeon 
           v: kernel bus ID: 00:01.0 chip ID: 1002:9806 
           Display: x11 server: X.Org 1.20.4 driver: radeon resolution: 1600x900~60Hz 
           OpenGL: renderer: AMD PALM (DRM 2.50.0 / 4.19.0-12-amd64 LLVM 7.0.1) v: 3.3 Mesa 18.3.6 compat-v: 3.1 
           direct render: Yes 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] Wrestler HDMI Audio vendor: Hewlett-Packard driver: snd_hda_intel 
           v: kernel bus ID: 00:01.1 chip ID: 1002:1314 
           Device-2: Advanced Micro Devices [AMD/ATI] SBx00 Azalia vendor: Hewlett-Packard driver: snd_hda_intel v: kernel 
           bus ID: 00:14.2 chip ID: 1002:4383 
           Sound Server: ALSA v: k4.19.0-12-amd64 
Network:   Device-1: Broadcom Limited NetLink BCM57781 Gigabit Ethernet PCIe vendor: Hewlett-Packard driver: tg3 v: 3.137 
           port: f100 bus ID: 03:00.0 chip ID: 14e4:16b1 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 341.39 GiB used: 4.95 GiB (1.4%) 
           ID-1: /dev/sda vendor: Hitachi model: HTS543232A7A384 size: 298.09 GiB speed: 3.0 Gb/s rotation: 5400 rpm 
           serial: <filter> rev: A60W temp: 30 C scheme: GPT 
           ID-2: /dev/sdb type: USB vendor: Verbatim model: OTG Tiny size: 28.86 GiB serial: <filter> rev: PMAP scheme: GPT 
           ID-3: /dev/sdc type: USB vendor: Toshiba model: TransMemory size: 14.44 GiB serial: <filter> scheme: MBR 
Partition: ID-1: / size: 28.83 GiB used: 4.95 GiB (17.2%) fs: f2fs dev: /dev/sdb2 
Sensors:   System Temperatures: cpu: 45.5 C mobo: N/A gpu: radeon temp: 45 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 168 Uptime: 5m Memory: 3.33 GiB used: 815.5 MiB (23.9%) Init: SysVinit v: 2.93 runlevel: 5 default: 5 
           Compilers: gcc: 8.3.0 alt: 8 Shell: bash (su) v: 5.0.3 running in: xfce4-terminal inxi: 3.0.36 
`

**Comment by agnivo007** [comment]
Redo Rescue Version : v3.0.1
System Manufacturer / Model : Dell / Latitude E6230 Laptop
Booting Mode : UEFI
SecureBoot : Disabled
Booting to Redo App? : Yes
Working as expected? : Yes
Other Comments : I use a Ventoy (www.ventoy.net) multiboot usb drive, just copy the ISO and boot off it.

System Info :
`Machine:   Type: Laptop System: Dell product: Latitude E6230 v: 01 serial: <filter> 
           Mobo: Dell model: 0R6V5Y v: A00 serial: <filter> UEFI: Dell v: A20 date: 11/30/2018 
Memory:    RAM: total: 5.78 GiB used: 908.4 MiB (15.4%) 
           Array-1: capacity: 16 GiB slots: 2 EC: None 
           Device-1: DIMM A size: 4 GiB speed: 1333 MT/s 
           Device-2: DIMM B size: 2 GiB speed: 1333 MT/s 
CPU:       Topology: Dual Core model: Intel Core i5-3320M bits: 64 type: MT MCP L2 cache: 3072 KiB 
           Speed: 1619 MHz min/max: 1200/3300 MHz Core speeds (MHz): 1: 1619 2: 2127 3: 1690 4: 1743 
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel 
           Display: server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 20.1.8 
Network:   Device-1: Intel 82579LM Gigabit Network driver: e1000e 
           IF: eth0 state: down mac: <filter> 
           Device-2: Broadcom Limited BCM43228 802.11a/b/g/n driver: wl 
           IF: wlan0 state: up mac: <filter> 
Drives:    Local Storage: total: 115.53 GiB used: 7.70 GiB (6.7%) 
           ID-1: /dev/mmcblk0 model: 00000 size: 59.62 GiB 
           ID-2: /dev/sda vendor: Intel model: SSDSC2CW060A3 size: 55.90 GiB `

**Comment by IlgazC** [comment]
Redo Rescue Version : v3.03 BETA
System Manufacturer / Model :HP Pavilion X360 PC (13 ")
Booting Mode : UEFI / BIOS-Legacy UEFI
SecureBoot : Enabled / Disabled / NA ENABLED/DISABLED
Booting to Redo App? : Yes / No Yes
Working as expected? : Yes / No Yes
`Machine:   Type: Laptop System: Hewlett-Packard product: HP Pavilion 13 x360 PC v: 0977120000405F00000410180 serial: <filter> 
           Mobo: Hewlett-Packard model: 2341 v: 07.0A serial: <filter> UEFI: Insyde v: F.41 date: 06/21/2018 
Memory:    RAM: total: 7.70 GiB used: 1.96 GiB (25.4%) 
           Array-1: capacity: 16 GiB slots: 2 EC: None 
           Device-1: Bottom-Slot 1(left) size: 8 GiB speed: 1600 MT/s 
           Device-2: Bottom-Slot 2(right) size: No Module Installed 
CPU:       Info: Dual Core model: Intel Core i5-5200U bits: 64 type: MT MCP L2 cache: 3072 KiB 
           Speed: 2196 MHz min/max: 500/2700 MHz Core speeds (MHz): 1: 2196 2: 2195 3: 2195 4: 2195 
Graphics:  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel 
           Device-2: Realtek HP Truevision HD integrated webcam type: USB driver: uvcvideo 
           Display: server: X.Org 1.20.9 driver: modesetting resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 20.2.1 
Network:   Device-1: Broadcom and subsidiaries BCM43142 802.11b/g/n driver: N/A 
           Device-2: Realtek RTL810xE PCI Express Fast Ethernet driver: r8169 
           IF: eno1 state: down mac: <filter> 
           Device-3: HP 802.11ac NIC type: USB driver: usblp 
           Device-4: Realtek 802.11ac NIC type: USB driver: rtl8821cu 
           IF: wlp0s20u2 state: up mac: <filter> 
Drives:    Local Storage: total: 1.60 TiB used: 746.15 GiB (45.6%) 
           ID-1: /dev/sda vendor: Apacer model: APS-SL3N-240 size: 223.57 GiB 
           ID-2: /dev/sdb type: USB vendor: Kingston model: DataTraveler 3.0 size: 14.41 GiB 
           ID-3: /dev/sdc type: USB model: USB 3.0 super high speed size: 465.76 GiB 
           ID-4: /dev/sdd type: USB vendor: Western Digital model: WD Elements 2620 size: 931.48 GiB 
`

**Comment by agnivo007** [comment]
Seems things are ok now with the latest release, closing issue. Feel free to open if needed in future.
