### ISSUE TITLE
What is root password?

### ISSUE THREAD

**Issue by pnxtm** [redorescue/redorescue#57]
After some inactivity, system locked and now it displays login page, but I don't know root password.

**Comment by agnivo007** [comment]
Did you try root / redo ? @zebradots will give you the exact one if you wait. Also, I think it should be documented on site.

**Comment by pnxtm** [comment]
> Did you try root / redo ? @zebradots will give you the exact one if you wait. Also, I think it should be documented on site.

Yeah it's root:redo. Should be documented somewhere.

**Comment by zebradots** [comment]
Correct, the password is `redo`, and this has now been added to the **Notes** section of the README.md with commit https://github.com/redorescue/redorescue/commit/15beff1d6dbe7183ed9bfde8308f2901c1181059.
