### ISSUE TITLE
Login prompt: startx not loading with NVIDIA 1660 GTX

### ISSUE THREAD

**Issue by nitrostemp** [redorescue/redorescue#58]
when i start redo on my pc i am getting thrown to the login prompt which when I log in and press startx it throws the error no displays found. is there a quick fix for this?

**Comment by agnivo007** [comment]
Have you tried safe boot option?

**Comment by nitrostemp** [comment]
> Have you tried safe boot option?

yes, i tried safe boot, same issue occurred

**Comment by zebradots** [comment]
Out of curiosity, are you able to boot from the Debian 10 Live DVD image, or do you encounter the same issue?

GPU support seems more limited on Debian 10, unfortunately. You can also try booting the latest version in the Redo 2.0 branch to see if Debian 9 boots properly.

**Comment by zebradots** [comment]
Were you able to boot into Debian 10 live (not the installer)?

**Comment by zebradots** [comment]
See #60
