### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [redorescue/redorescue#6]
It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the "redorescue" organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by redorescue** [comment]
Thank you for providing the helpful links! We'll be converting the existing account to an organization soon.

**Comment by zebradots** [comment]
Migration completed! Closing this issue.

**Comment by Neustradamus** [comment]
@zebradots: Thanks a lot!

Add you in people section of the organization :)

**Comment by zebradots** [comment]
Done. Thank you for your help!

**Comment by Neustradamus** [comment]
@zebradots: You are not in public list: https://github.com/orgs/redorescue/people ;)

**Comment by zebradots** [comment]
@Neustradamus: Thanks for pointing this out! @zebradots should now be listed publicly.

**Comment by Neustradamus** [comment]
@zebradots: Thanks :)
