### ISSUE TITLE
Mounting an NTFS source partition hangs the application

### ISSUE THREAD

**Issue by redorescue** [redorescue/redorescue#7]
When selecting an NTFS partition for a restore operation, the application hangs with the "Checking source drive..." spinner.

Oddly, the partition is mounted just fine, but the user can't continue.

The only visible difference between this filesystem and the others that work (such as EXT3) is that NTFS mounts are reported as `type fuseblk`.

If all else fails, it may be possible to hand this command off to the `redo-monitor` service for execution in the background, but ideally there is a way to run it directly.

In the meantime, adding the ability to close the spinner window will help scenarios like this which would otherwise render the application unresponsive.

**Comment by redorescue** [comment]
NTFS-3g FUSE mounts cause PHP to hang indefinitely, even though the operation completes successfully. We've updated the `mount_drive()` to hand off all local mounts to the `redo` service to resolve this issue. This solution imposes a 2-second delay to ensure the 1-second polling of the `redo` service has enough time to complete the mount before it gets verified.

Closing this issue.

**Comment by candrapersada** [comment]
why mount NTFS partitions error?
