### ISSUE TITLE
Unable to start on a ASUS PN41

### ISSUE THREAD

**Issue by cesco78** [redorescue/redorescue#79]
Hi,
I have 11 Asus PN41 to clone, but the actual version won't start on them, i think for a problem with he USBC controller:

`uscs_acpi USBC000:00 PPM init failed (-110)`

Someone could help me please?

I cannnot disable the controller
Thanks

**Comment by zebradots** [comment]
@cesco78: Please try the 4.0.0 release based on Debian 11 to see if this issue is resolved. It should be available within hours.
