### ISSUE TITLE
Add ability to verify the integrity of a backup image

### ISSUE THREAD

**Issue by redorescue** [redorescue/redorescue#8]
At the welcome screen, the user should be presented with three options:

- Backup
- _Verify_
- Restore

While **Redo is committed to utmost simplicity and is guided by the Unix Philosophy**, this third and final button is critical for users to be able to trust the integrity of the backup image and be able to verify it without performing a complete restore to a physical (or virtual) drive.

This feature is currently under development and will be merged as soon as it is complete.

**Comment by redorescue** [comment]
This feature was added with the latest commit:
https://github.com/redorescue/redorescue/commit/c250978c8e11e2d0c6d35e7d1e275fe4f97d9412

**Comment by redorescue** [comment]
This issue will be closed once the new release is tagged.

**Comment by zebradots** [comment]
Release 2.0.1 tag has been added. This feature is now included in the latest release.
