### ISSUE TITLE
fix boot after restore linux

### ISSUE THREAD

**Issue by candrapersada** [redorescue/redorescue#9]
how to fix boot after restore linux? and why backup loading slow for Version 2.0.0 (2020-06-11) BETA?
![VirtualBox_Linux Mint VirtualBox_18_06_2020_16_52_04](https://user-images.githubusercontent.com/36833664/85006783-c65cee80-b184-11ea-9333-974d6071f8a7.png)

**Comment by redorescue** [comment]
Thanks for testing the beta release! It seems there may be two separate issues here.

First, your screenshot seems to be related to issue #7 with mounting NTFS partitions. We are working on that now, and it may not be possible to save a backup to an NTFS filesystem or restore from NTFS until the next image is released.

Second, it sounds as though you successfully created a backup with version 2.0.0 and then restored it, but were unable to boot Linux afterward. Is this correct? If so, we need to get more information about which version of Linux you are running so we can try to determine what went wrong. What happens when you try to boot? Are there any GRUB errors given?

**Comment by candrapersada** [comment]
KDE Neon partition mbr

**Comment by redorescue** [comment]
Question: Which restore mode was used, baremetal or selective? And if selective, were any of the partitions remapped to different locations?

**Comment by candrapersada** [comment]
selective, partition logical to primary

**Comment by redorescue** [comment]
It is not surprising that the system will not boot if partitions are remapped on a drive that contains an operating system. This is for two reasons:

1. The master boot loader will point a specific partition and it will not find what it needs, and
2. A selective restore does not write the MBR at all, so unless the boot loader is present and already functions, this will never result in a bootable drive (particularly if restoring to a newly-partitioned drive).

Unfortunately fixing this is different and quirky for each boot loader (GRUB, Windows, etc.) and while there may be ways to fix each different one, we aren't aware of any bulletproof solution that works for all of them every time.

We may need to add language that better explains what these two options achieve. In your scenario we recommend trying the baremetal backup mode and seeing if this restores the operating system's ability to boot (but understand that the entire MBR and partition table will be overwritten if you do this). Note also that no matter what type of restore you try, the backup always contains the necessary MBR and partition table information (even if you choose not to restore them).

Hopefully this information is somewhat helpful. Let us know if you have any other input or ideas on how we could improve this situation for your use case.

**Comment by zebradots** [comment]
Bare metal mode overwrites the MBR and partition tables. Selective mode preserves all existing MBR and partition table information, and only writes data to existing partitions. This may be confusing to the typical user. A potential path forward may be to include a prominent warning on the selective restore tab explaining that operating systems will not boot if their partitions are remapped. Thoughts?

**Comment by zebradots** [comment]
The first part of this issue, the NTFS partition hang, has been corrected in the latest release. The second part is essentially identical to issue #10, and has been corrected with the latest commit https://github.com/redorescue/redorescue/commit/e13e9550eafb0945d782a8906ab68fd39e92a949 which reminds users that shuffling operating system partitions around will make your restored system unbootable.

Closing this issue.
